import { db } from '~/db'
import {
    brandsTable,
    productsTable,
    typesTable,
    usersTable,
} from './schema';

await db.execute(`SET FOREIGN_KEY_CHECKS = 0`)
await db.execute(`TRUNCATE TABLE brands_table`);
await db.execute(`TRUNCATE TABLE types_table`);
await db.execute(`TRUNCATE TABLE products_table`);
await db.execute(`SET FOREIGN_KEY_CHECKS = 1`)

await db.insert(brandsTable).values([
    { name: 'Akko' },
    { name: 'Gateron' },
    { name: 'Outemu' },
]);

await db.insert(typesTable).values([
    { name: 'Linear' },
    { name: 'Tactile' },
    { name: 'Clicky' },
]);

await db.insert(productsTable).values([
    {
        brand_id: 1,
        name: 'V3 Cream Yellow Pro',
        type_id: 1,
        description: 'The Akko Cream Yellow Pro V3 switches are a standout choice for budget-conscious mechanical keyboard enthusiasts. Right out of the box, these switches offer a satisfying combination of a poppy, clacky sound and a decent smoothness, ideal for those who favor a vibrant auditory experience paired with a creamy feel.',
        price: 119.75,
        actuation: 50,
        bottom_out: 60,
        total_travel: 3.3,
        mount_type: 5,
        top_housing: 'Polycarbonate',
        bottom_housing: 'Nylon',
        lubed: true,
    },
    {
        brand_id: 1,
        name: 'Rosewood',
        type_id: 1,
        description: 'These Rosewood switches produce a deep, satisfying thocky sound straight out of the box, thanks to a thin layer of factory-applied lubricant.',
        price: 180,
        actuation: 40,
        bottom_out: 50,
        total_travel: 4,
        mount_type: 5,
        top_housing: 'Nylon',
        bottom_housing: 'Nylon',
        lubed: true,
    },
    {
        brand_id: 2,
        name: 'Baby Kangaroo (V2)',
        type_id: 2,
        description: 'We are super excited to be offering these Baby Kangaroo switches. We experience a crisp, light switch-like tactility along with a marbley sound profile when using them.',
        price: 324.86,
        actuation: 59,
        bottom_out: 67,
        total_travel: 3.4,
        mount_type: 5,
        top_housing: 'Polycarbonate',
        bottom_housing: 'Nylon',
        lubed: true,
    },
    {
        brand_id: 2,
        name: 'Melodic',
        type_id: 3,
        description: 'Gateron reinvigorates the clicky switch category with the introduction of the Gateron Melodic. By infusing recent advancements such as smooth factory lubing and dual-railed stems into this clicky switch, Gateron ensures users can relish the classic clicky sound and tactile feedback without compromising on smoothness.',
        price: 350,
        bottom_out: 60,
        total_travel: 4,
        mount_type: 5,
        top_housing: 'Polycarbonate',
        bottom_housing: 'Nylon',
        lubed: true,
    },
    {
        brand_id: 2,
        name: 'Milky Yellow Pro (KS-3)',
        type_id: 1,
        description: "The Gateron Milky Yellow Pro is the epitome of a classic budget switch. This all-rounder linear switch from Gateron embodies smoothness and buttery goodness. With its low, 'thocky' sound and satisfyingly thick resistance, it excels in both gaming and typing, making it a perfect all-purpose switch. It's therefore no surprise that these Milky Yellows are the go- to switch for budget enthusiasts",
        price: 135,
        bottom_out: 50,
        actuation: 62,
        total_travel: 4,
        mount_type: 5,
        top_housing: 'Nylon',
        bottom_housing: 'Nylon',
        lubed: true,
    },
    {
        brand_id: 3,
        name: 'Blue Jade',
        type_id: 3,
        description: 'The Outemu Blue Jade is a standout clicky switch that captures everything people love about a crisp, tactile typing experience. With its sharp click, punchy tactile bump, and satisfyingly firm resistance, this switch delivers that classic clicky feedback — bold, bright, and unmistakably expressive. The Blue Jade excels in both typing and casual gaming, offering a lively feel that makes every keystroke enjoyable.',
        price: 179.98,
        bottom_out: 50,
        actuation: 65,
        total_travel: 4,
        mount_type: 3,
        top_housing: 'Nylon',
        bottom_housing: 'Nylon',
        lubed: true,
    },
    {
        brand_id: 3,
        name: 'Lime (V3)',
        type_id: 2,
        description: 'These Lime switches are incredibly unique in that they are lightweight, feature an approachable tactility, and are silenced. As such, these switches are perfect for tactile fans who want a feathery light typing experience with just a touch of tactility.',
        price: 200,
        bottom_out: 35,
        actuation: 45,
        total_travel: 3.3,
        mount_type: 5,
        top_housing: 'Nylon',
        bottom_housing: 'Nylon',
        lubed: true,
    },
    {
        brand_id: 3,
        name: 'Dustproof Silent Ocean',
        type_id: 1,
        description: 'The Outemu Dustproof Silent Ocean is a smooth, ultra-quiet linear switch built for clean, effortless typing. With its gentle resistance, soft bottom-out, and dampened sound profile, it delivers a whisper-quiet experience perfect for work, gaming, or late-night sessions. Loved by budget builders for its silence and reliability, the Silent Ocean is an excellent pick for anyone wanting a calm, refined typing feel without sacrificing performance.',
        price: 179.98,
        bottom_out: 45,
        actuation: 65,
        total_travel: 3.3,
        mount_type: 3,
        top_housing: 'Polycarbonate',
        bottom_housing: 'Nylon',
        lubed: true,
    },
]);